#!/bin/bash

source ./utils/utils.sh

LogStarted "=====================================> Provisioning infra via terraform.."

cd tf
terraform apply -auto-approve
cd ..

Log "sleeping to wait for instances to initialise.."
sleep 10

LogElapsedDuration

LogCompleted "Done."
exit 0
